project:
  type: book
  output-dir: html

book:
 title: "LPIS v QGIS"
 author:
   - name: Václav Štěpán 
     email: vaclav.stepan@fjfi.cvut.cz
 chapters:
   - index.md
   - lpis.md
   - rizika.md
   - dpb-pp.md
   - pilot2.md
   - ugcs.md
   - livestream.md
   - todo.md

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

lang: cs
date: today
date-format: iso

bibliography: literatura.bib
reference-section-title: Literatura
csl: iso690-numeric-brackets-cs.csl
